### ISSUE TITLE
AFE AUX PSU connection crossed

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Shuttler#35]
Shuttler AFE was supposed to be compatible with AUX PSU:
![image](https://user-images.githubusercontent.com/9166701/220872891-4a36e364-f46a-4102-8afb-b6558118045d.png)
However, this would require crossed cable (1-3 crossed):
![image](https://user-images.githubusercontent.com/9166701/220873081-51696141-1b65-4bdd-8058-c6a5d8f376c0.png)

**Comment by gkasprow** [comment]
We would make cables anyway. They are usually available with a plug on one side.
But it's good to fix it in new revision

**Comment by kaolpr** [comment]
Can we still make it to v1.1?

**Comment by gkasprow** [comment]
yes
Did we produce the v1.0 prototypes?

**Comment by kaolpr** [comment]
Yes. We have one.

**Comment by gkasprow** [comment]
fixed
![image](https://user-images.githubusercontent.com/4325054/221580479-5f5a1aac-b37b-4f4c-9aa4-cda270c17f95.png)

**Comment by maciejprzybysz** [comment]
In v1.1 the pinout is still incorrect.

![2024-01-22_13h41_29](https://github.com/sinara-hw/Shuttler/assets/48446953/f38d10d0-1c5c-4173-a7d9-fda5206b22ee)

**Comment by maciejprzybysz** [comment]
AUX_PSU would be updated, Shuttler AFE will be not changed.
